# Generated by Django 5.1.7 on 2025-03-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='book_number',
        ),
    ]
