# Generated by Django 5.1.7 on 2025-03-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_rename_isbn_book_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
